<?php

namespace Apb\TypikaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends EntityRepository
{
    /**
     * {@inheritDoc}
     * 
     * @return array The entities.
     */
    public function findBy(array $criteria, array $orderBy = array('nom' => 'asc'), $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
