apb_base:
    resource: "@ApbBaseBundle/Controller/"
    type:     annotation
    prefix:   /

#ApbTypikaBundle
apb_typika:
    resource: "@ApbTypikaBundle/Controller/"
    type:     annotation
    prefix:   /typika

apb_typika_redirect:
    pattern:   /Typika/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: apb_typika_default_index }

#ApbDiathequeBundle
apb_diatheque:
    resource: "@ApbDiathequeBundle/Controller/"
    type:     annotation
    prefix:   /diatheque

apb_diatheque_redirect:
    pattern:   /Diatheque/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: apb_diatheque_default_index }

#ApbMonumentsBundle
apb_monuments:
    resource: "@ApbMonumentsBundle/Controller/"
    type:     annotation
    prefix:   /monuments

apb_monuments_redirect:
    pattern:   /Monuments/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: apb_monuments_default_index }


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

# fos_user_group:
#     resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#     prefix: /group

#SonataAdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#SonataUserBundle
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

#SonataMediaBundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
